// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Open_lab.Data;

#nullable disable

namespace Open_lab.Migrations
{
    [DbContext(typeof(OpenLabDbContext))]
    [Migration("20260416172229_AddUserSaltAndLegacyPasswordUpgrade")]
    partial class AddUserSaltAndLegacyPasswordUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Open_lab.Models.Antibiotic", b =>
                {
                    b.Property<int>("AntibioticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntibioticId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntibioticId");

                    b.ToTable("Antibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceLog", b =>
                {
                    b.Property<int>("AttendanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceLogId"));

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("Open_lab.Models.Culture", b =>
                {
                    b.Property<int>("CultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultureId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CultureId");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("Open_lab.Models.CultureAntibiotic", b =>
                {
                    b.Property<int>("CultureId")
                        .HasColumnType("int");

                    b.Property<int>("AntibioticId")
                        .HasColumnType("int");

                    b.HasKey("CultureId", "AntibioticId");

                    b.HasIndex("AntibioticId");

                    b.ToTable("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroup", b =>
                {
                    b.Property<int>("CustomGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomGroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomGroupId");

                    b.ToTable("CustomGroups");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroupItem", b =>
                {
                    b.Property<int>("CustomGroupItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomGroupItemId"));

                    b.Property<int>("CustomGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("CustomGroupItemId");

                    b.HasIndex("CustomGroupId");

                    b.HasIndex("TestId");

                    b.ToTable("CustomGroupItems");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Open_lab.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("LabId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Open_lab.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceListId"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.HasKey("PriceListId");

                    b.HasIndex("ReferralId");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("Open_lab.Models.PriceListItem", b =>
                {
                    b.Property<int>("PriceListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceListItemId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("PriceListItemId");

                    b.HasIndex("PriceListId");

                    b.HasIndex("TestId");

                    b.ToTable("PriceListItems");
                });

            modelBuilder.Entity("Open_lab.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Open_lab.Models.ResultValue", b =>
                {
                    b.Property<int>("ResultValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultValueId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("VisitTestId")
                        .HasColumnType("int");

                    b.HasKey("ResultValueId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("VerifiedBy");

                    b.HasIndex("VisitTestId");

                    b.ToTable("ResultValues");
                });

            modelBuilder.Entity("Open_lab.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Open_lab.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Open_lab.Models.SampleCollection", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleId"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitTestId")
                        .HasColumnType("int");

                    b.HasKey("SampleId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("VisitTestId")
                        .IsUnique();

                    b.ToTable("SampleCollections");
                });

            modelBuilder.Entity("Open_lab.Models.SampleType", b =>
                {
                    b.Property<int>("SampleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SampleTypeId");

                    b.ToTable("SampleTypes");
                });

            modelBuilder.Entity("Open_lab.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRoutine")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSendOut")
                        .HasColumnType("bit");

                    b.Property<string>("NameReceipt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TurnaroundHours")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.TestComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("TestId");

                    b.ToTable("TestComments");
                });

            modelBuilder.Entity("Open_lab.Models.TestGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ParameterId");

                    b.HasIndex("TestId");

                    b.HasIndex("UnitId");

                    b.ToTable("TestParameters");
                });

            modelBuilder.Entity("Open_lab.Models.TestReferenceRange", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeId"));

                    b.Property<int?>("AgeFrom")
                        .HasColumnType("int");

                    b.Property<int?>("AgeTo")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HighValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LowValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NormalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("RangeId");

                    b.HasIndex("TestId");

                    b.ToTable("TestReferenceRanges");
                });

            modelBuilder.Entity("Open_lab.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Open_lab.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Open_lab.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferralId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.Property<int>("VisitTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitTestId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceLog", b =>
                {
                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.CultureAntibiotic", b =>
                {
                    b.HasOne("Open_lab.Models.Antibiotic", "Antibiotic")
                        .WithMany("CultureAntibiotics")
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Culture", "Culture")
                        .WithMany("CultureAntibiotics")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antibiotic");

                    b.Navigation("Culture");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroupItem", b =>
                {
                    b.HasOne("Open_lab.Models.CustomGroup", "CustomGroup")
                        .WithMany("Items")
                        .HasForeignKey("CustomGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("CustomGroupItems")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomGroup");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.HasOne("Open_lab.Models.Visit", "Visit")
                        .WithOne("Invoice")
                        .HasForeignKey("Open_lab.Models.Invoice", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Open_lab.Models.Payment", b =>
                {
                    b.HasOne("Open_lab.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("PriceLists")
                        .HasForeignKey("ReferralId");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.PriceListItem", b =>
                {
                    b.HasOne("Open_lab.Models.PriceList", "PriceList")
                        .WithMany("Items")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("PriceListItems")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.ResultValue", b =>
                {
                    b.HasOne("Open_lab.Models.TestParameter", "Parameter")
                        .WithMany("ResultValues")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "VerifiedByUser")
                        .WithMany("VerifiedResults")
                        .HasForeignKey("VerifiedBy");

                    b.HasOne("Open_lab.Models.VisitTest", "VisitTest")
                        .WithMany("ResultValues")
                        .HasForeignKey("VisitTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("VerifiedByUser");

                    b.Navigation("VisitTest");
                });

            modelBuilder.Entity("Open_lab.Models.RolePermission", b =>
                {
                    b.HasOne("Open_lab.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Open_lab.Models.SampleCollection", b =>
                {
                    b.HasOne("Open_lab.Models.User", "CollectedByUser")
                        .WithMany("SampleCollections")
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.VisitTest", "VisitTest")
                        .WithOne("SampleCollection")
                        .HasForeignKey("Open_lab.Models.SampleCollection", "VisitTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectedByUser");

                    b.Navigation("VisitTest");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.HasOne("Open_lab.Models.TestGroup", "Group")
                        .WithMany("Tests")
                        .HasForeignKey("GroupId");

                    b.HasOne("Open_lab.Models.SampleType", "SampleType")
                        .WithMany("Tests")
                        .HasForeignKey("SampleTypeId");

                    b.HasOne("Open_lab.Models.Unit", "Unit")
                        .WithMany("Tests")
                        .HasForeignKey("UnitId");

                    b.Navigation("Group");

                    b.Navigation("SampleType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Open_lab.Models.TestComment", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("Comments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("Parameters")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Unit", "Unit")
                        .WithMany("TestParameters")
                        .HasForeignKey("UnitId");

                    b.Navigation("Test");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Open_lab.Models.TestReferenceRange", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.UserRole", b =>
                {
                    b.HasOne("Open_lab.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.HasOne("Open_lab.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("Visits")
                        .HasForeignKey("ReferralId");

                    b.Navigation("Patient");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("VisitTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Visit", "Visit")
                        .WithMany("VisitTests")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Open_lab.Models.Antibiotic", b =>
                {
                    b.Navigation("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.Culture", b =>
                {
                    b.Navigation("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Open_lab.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Open_lab.Models.Referral", b =>
                {
                    b.Navigation("PriceLists");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Open_lab.Models.SampleType", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CustomGroupItems");

                    b.Navigation("Parameters");

                    b.Navigation("PriceListItems");

                    b.Navigation("ReferenceRanges");

                    b.Navigation("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.TestGroup", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.Navigation("ResultValues");
                });

            modelBuilder.Entity("Open_lab.Models.Unit", b =>
                {
                    b.Navigation("TestParameters");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.User", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("Payments");

                    b.Navigation("SampleCollections");

                    b.Navigation("UserRoles");

                    b.Navigation("VerifiedResults");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.Navigation("ResultValues");

                    b.Navigation("SampleCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
