// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Open_lab.Data;

#nullable disable

namespace Open_lab.Migrations
{
    [DbContext(typeof(OpenLabDbContext))]
    [Migration("20260526180401_F15_AddUserHashVersion")]
    partial class F15_AddUserHashVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Open_lab.Models.AdditionalCharge", b =>
                {
                    b.Property<int>("AdditionalChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdditionalChargeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.HasKey("AdditionalChargeId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("AdditionalCharges");
                });

            modelBuilder.Entity("Open_lab.Models.Antibiotic", b =>
                {
                    b.Property<int>("AntibioticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntibioticId"));

                    b.Property<bool>("IsSafeForChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSafeForPregnancy")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntibioticId");

                    b.ToTable("Antibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceBreak", b =>
                {
                    b.Property<int>("BreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreakId"));

                    b.Property<int>("AttendanceLogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BreakId");

                    b.HasIndex("AttendanceLogId", "StartAt");

                    b.ToTable("AttendanceBreaks");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceDayStatus", b =>
                {
                    b.Property<int>("DayStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayStatusId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DayStatusId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceDayStatuses");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceLog", b =>
                {
                    b.Property<int>("AttendanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceLogId"));

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceLogId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("Open_lab.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Open_lab.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Open_lab.Models.ContractInvoice", b =>
                {
                    b.Property<int>("ContractInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractInvoiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContractInvoiceId");

                    b.HasIndex("ReferralId");

                    b.ToTable("ContractInvoices");
                });

            modelBuilder.Entity("Open_lab.Models.Culture", b =>
                {
                    b.Property<int>("CultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultureId"));

                    b.Property<int>("ColonyCount")
                        .HasColumnType("int");

                    b.Property<string>("GrowthConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsolatedOrganism")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CultureId");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("Open_lab.Models.CultureAntibiotic", b =>
                {
                    b.Property<int>("CultureId")
                        .HasColumnType("int");

                    b.Property<int>("AntibioticId")
                        .HasColumnType("int");

                    b.HasKey("CultureId", "AntibioticId");

                    b.HasIndex("AntibioticId");

                    b.ToTable("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroup", b =>
                {
                    b.Property<int>("CustomGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomGroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomGroupId");

                    b.ToTable("CustomGroups");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroupItem", b =>
                {
                    b.Property<int>("CustomGroupItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomGroupItemId"));

                    b.Property<int>("CustomGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("CustomGroupItemId");

                    b.HasIndex("CustomGroupId");

                    b.HasIndex("TestId");

                    b.ToTable("CustomGroupItems");
                });

            modelBuilder.Entity("Open_lab.Models.DoctorCommission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCalculated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("CommissionId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("VisitId");

                    b.ToTable("DoctorCommissions");
                });

            modelBuilder.Entity("Open_lab.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Open_lab.Models.ExternalLabQueue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueueId"));

                    b.Property<DateTime>("DateQueued")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitTestId")
                        .HasColumnType("int");

                    b.HasKey("QueueId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("VisitTestId")
                        .IsUnique();

                    b.ToTable("ExternalLabQueues");
                });

            modelBuilder.Entity("Open_lab.Models.ExternalLabSettlement", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SettlementId");

                    b.HasIndex("ReferralId");

                    b.ToTable("ExternalLabSettlements");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractInvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ContractInvoiceId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Open_lab.Models.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAnemia")
                        .HasColumnType("bit");

                    b.Property<bool>("HasChronicDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("HasJointInflammation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasKidneyFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPregnancyComplication")
                        .HasColumnType("bit");

                    b.Property<string>("Medications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("Open_lab.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AgeUnit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<string>("LabId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("LabId")
                        .IsUnique();

                    b.HasIndex("NationalId");

                    b.HasIndex("ReferralId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Open_lab.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Open_lab.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhysicianId");

                    b.HasIndex("PriceListId");

                    b.ToTable("Physicians");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceListId"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.HasKey("PriceListId");

                    b.HasIndex("ReferralId");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("Open_lab.Models.PriceListItem", b =>
                {
                    b.Property<int>("PriceListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceListItemId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("PriceListItemId");

                    b.HasIndex("PriceListId");

                    b.HasIndex("TestId");

                    b.ToTable("PriceListItems");
                });

            modelBuilder.Entity("Open_lab.Models.Reagent", b =>
                {
                    b.Property<int>("ReagentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReagentId"));

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReagentId");

                    b.ToTable("Reagents");
                });

            modelBuilder.Entity("Open_lab.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommissionPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Open_lab.Models.ResultValue", b =>
                {
                    b.Property<int>("ResultValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultValueId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("VisitTestId")
                        .HasColumnType("int");

                    b.HasKey("ResultValueId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("VerifiedBy");

                    b.HasIndex("VisitTestId");

                    b.ToTable("ResultValues");
                });

            modelBuilder.Entity("Open_lab.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Open_lab.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Open_lab.Models.SampleCollection", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleId"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsExternalSample")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeparated")
                        .HasColumnType("bit");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitTestId")
                        .HasColumnType("int");

                    b.HasKey("SampleId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("VisitTestId")
                        .IsUnique();

                    b.ToTable("SampleCollections");
                });

            modelBuilder.Entity("Open_lab.Models.SampleType", b =>
                {
                    b.Property<int>("SampleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SampleTypeId");

                    b.ToTable("SampleTypes");
                });

            modelBuilder.Entity("Open_lab.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Open_lab.Models.ShiftSchedule", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("ShiftSchedules");
                });

            modelBuilder.Entity("Open_lab.Models.ShipmentItem", b =>
                {
                    b.Property<int>("ShipmentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentItemId"));

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.HasKey("ShipmentItemId");

                    b.HasIndex("ManifestId");

                    b.HasIndex("QueueId")
                        .IsUnique();

                    b.ToTable("ShipmentItems");
                });

            modelBuilder.Entity("Open_lab.Models.ShipmentManifest", b =>
                {
                    b.Property<int>("ManifestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManifestId"));

                    b.Property<string>("CourierNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShipped")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManifestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManifestId");

                    b.HasIndex("ReferralId");

                    b.ToTable("ShipmentManifests");
                });

            modelBuilder.Entity("Open_lab.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRoutine")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSendOut")
                        .HasColumnType("bit");

                    b.Property<string>("NameReceipt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PatientPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReportOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TurnaroundHours")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.TestComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("LowComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ParameterId");

                    b.HasIndex("TestId");

                    b.ToTable("TestComments");
                });

            modelBuilder.Entity("Open_lab.Models.TestConsumption", b =>
                {
                    b.Property<int>("ConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumptionId"));

                    b.Property<decimal>("AmountPerTest")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReagentId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("ConsumptionId");

                    b.HasIndex("ReagentId");

                    b.HasIndex("TestId");

                    b.ToTable("TestConsumptions");
                });

            modelBuilder.Entity("Open_lab.Models.TestGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ParameterId");

                    b.HasIndex("TestId");

                    b.HasIndex("UnitId");

                    b.ToTable("TestParameters");
                });

            modelBuilder.Entity("Open_lab.Models.TestReferenceRange", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeId"));

                    b.Property<int?>("AgeFromDays")
                        .HasColumnType("int");

                    b.Property<string>("AgeFromUnit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("AgeFromValue")
                        .HasColumnType("int");

                    b.Property<int?>("AgeToDays")
                        .HasColumnType("int");

                    b.Property<string>("AgeToUnit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("AgeToValue")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HighValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LowValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NormalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("RangeId");

                    b.HasIndex("AgeFromDays");

                    b.HasIndex("AgeToDays");

                    b.HasIndex("ParameterId");

                    b.HasIndex("TestId");

                    b.ToTable("TestReferenceRanges");
                });

            modelBuilder.Entity("Open_lab.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Open_lab.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HashVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Open_lab.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferralId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.HasIndex("ReferralId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.Property<int>("VisitTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitTestId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReportOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.AdditionalCharge", b =>
                {
                    b.HasOne("Open_lab.Models.Invoice", "Invoice")
                        .WithMany("AdditionalCharges")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceBreak", b =>
                {
                    b.HasOne("Open_lab.Models.AttendanceLog", "AttendanceLog")
                        .WithMany("Breaks")
                        .HasForeignKey("AttendanceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceLog");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceDayStatus", b =>
                {
                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("AttendanceDayStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceLog", b =>
                {
                    b.HasOne("Open_lab.Models.ShiftSchedule", "Shift")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("ShiftId");

                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.AuditLog", b =>
                {
                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.ContractInvoice", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("ContractInvoices")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.CultureAntibiotic", b =>
                {
                    b.HasOne("Open_lab.Models.Antibiotic", "Antibiotic")
                        .WithMany("CultureAntibiotics")
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Culture", "Culture")
                        .WithMany("CultureAntibiotics")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antibiotic");

                    b.Navigation("Culture");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroupItem", b =>
                {
                    b.HasOne("Open_lab.Models.CustomGroup", "CustomGroup")
                        .WithMany("Items")
                        .HasForeignKey("CustomGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("CustomGroupItems")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomGroup");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.DoctorCommission", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Referral");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Open_lab.Models.Expense", b =>
                {
                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.ExternalLabQueue", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Open_lab.Models.VisitTest", "VisitTest")
                        .WithOne("ExternalQueueItem")
                        .HasForeignKey("Open_lab.Models.ExternalLabQueue", "VisitTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");

                    b.Navigation("VisitTest");
                });

            modelBuilder.Entity("Open_lab.Models.ExternalLabSettlement", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("Settlements")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.HasOne("Open_lab.Models.Branch", "Branch")
                        .WithMany("Invoices")
                        .HasForeignKey("BranchId");

                    b.HasOne("Open_lab.Models.ContractInvoice", "ContractInvoice")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractInvoiceId");

                    b.HasOne("Open_lab.Models.Visit", "Visit")
                        .WithOne("Invoice")
                        .HasForeignKey("Open_lab.Models.Invoice", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ContractInvoice");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Open_lab.Models.MedicalHistory", b =>
                {
                    b.HasOne("Open_lab.Models.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("Open_lab.Models.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Open_lab.Models.Patient", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("Patients")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.Payment", b =>
                {
                    b.HasOne("Open_lab.Models.Branch", "Branch")
                        .WithMany("Payments")
                        .HasForeignKey("BranchId");

                    b.HasOne("Open_lab.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Invoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.Physician", b =>
                {
                    b.HasOne("Open_lab.Models.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListId");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("PriceLists")
                        .HasForeignKey("ReferralId");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.PriceListItem", b =>
                {
                    b.HasOne("Open_lab.Models.PriceList", "PriceList")
                        .WithMany("Items")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("PriceListItems")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.ResultValue", b =>
                {
                    b.HasOne("Open_lab.Models.TestParameter", "Parameter")
                        .WithMany("ResultValues")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "VerifiedByUser")
                        .WithMany("VerifiedResults")
                        .HasForeignKey("VerifiedBy");

                    b.HasOne("Open_lab.Models.VisitTest", "VisitTest")
                        .WithMany("ResultValues")
                        .HasForeignKey("VisitTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("VerifiedByUser");

                    b.Navigation("VisitTest");
                });

            modelBuilder.Entity("Open_lab.Models.RolePermission", b =>
                {
                    b.HasOne("Open_lab.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Open_lab.Models.SampleCollection", b =>
                {
                    b.HasOne("Open_lab.Models.User", "CollectedByUser")
                        .WithMany("SampleCollections")
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Open_lab.Models.VisitTest", "VisitTest")
                        .WithOne("SampleCollection")
                        .HasForeignKey("Open_lab.Models.SampleCollection", "VisitTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectedByUser");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("VisitTest");
                });

            modelBuilder.Entity("Open_lab.Models.ShipmentItem", b =>
                {
                    b.HasOne("Open_lab.Models.ShipmentManifest", "Manifest")
                        .WithMany("Items")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.ExternalLabQueue", "QueueItem")
                        .WithOne("ShipmentItem")
                        .HasForeignKey("Open_lab.Models.ShipmentItem", "QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");

                    b.Navigation("QueueItem");
                });

            modelBuilder.Entity("Open_lab.Models.ShipmentManifest", b =>
                {
                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.HasOne("Open_lab.Models.TestGroup", "Group")
                        .WithMany("Tests")
                        .HasForeignKey("GroupId");

                    b.HasOne("Open_lab.Models.SampleType", "SampleType")
                        .WithMany("Tests")
                        .HasForeignKey("SampleTypeId");

                    b.HasOne("Open_lab.Models.Unit", "Unit")
                        .WithMany("Tests")
                        .HasForeignKey("UnitId");

                    b.Navigation("Group");

                    b.Navigation("SampleType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Open_lab.Models.TestComment", b =>
                {
                    b.HasOne("Open_lab.Models.TestParameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("Comments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.TestConsumption", b =>
                {
                    b.HasOne("Open_lab.Models.Reagent", "Reagent")
                        .WithMany("Consumptions")
                        .HasForeignKey("ReagentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reagent");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("Parameters")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Unit", "Unit")
                        .WithMany("TestParameters")
                        .HasForeignKey("UnitId");

                    b.Navigation("Test");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Open_lab.Models.TestReferenceRange", b =>
                {
                    b.HasOne("Open_lab.Models.TestParameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Open_lab.Models.UserRole", b =>
                {
                    b.HasOne("Open_lab.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.HasOne("Open_lab.Models.Branch", "Branch")
                        .WithMany("Visits")
                        .HasForeignKey("BranchId");

                    b.HasOne("Open_lab.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Physician", "Physician")
                        .WithMany("Visits")
                        .HasForeignKey("PhysicianId");

                    b.HasOne("Open_lab.Models.Referral", "Referral")
                        .WithMany("Visits")
                        .HasForeignKey("ReferralId");

                    b.Navigation("Branch");

                    b.Navigation("Patient");

                    b.Navigation("Physician");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.HasOne("Open_lab.Models.Test", "Test")
                        .WithMany("VisitTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Open_lab.Models.Visit", "Visit")
                        .WithMany("VisitTests")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Open_lab.Models.Antibiotic", b =>
                {
                    b.Navigation("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.AttendanceLog", b =>
                {
                    b.Navigation("Breaks");
                });

            modelBuilder.Entity("Open_lab.Models.Branch", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.ContractInvoice", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Open_lab.Models.Culture", b =>
                {
                    b.Navigation("CultureAntibiotics");
                });

            modelBuilder.Entity("Open_lab.Models.CustomGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Open_lab.Models.ExternalLabQueue", b =>
                {
                    b.Navigation("ShipmentItem");
                });

            modelBuilder.Entity("Open_lab.Models.Invoice", b =>
                {
                    b.Navigation("AdditionalCharges");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Open_lab.Models.Patient", b =>
                {
                    b.Navigation("MedicalHistory");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.Physician", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.PriceList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Open_lab.Models.Reagent", b =>
                {
                    b.Navigation("Consumptions");
                });

            modelBuilder.Entity("Open_lab.Models.Referral", b =>
                {
                    b.Navigation("ContractInvoices");

                    b.Navigation("Patients");

                    b.Navigation("PriceLists");

                    b.Navigation("Settlements");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Open_lab.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Open_lab.Models.SampleType", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.ShiftSchedule", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("Open_lab.Models.ShipmentManifest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Open_lab.Models.Test", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CustomGroupItems");

                    b.Navigation("Parameters");

                    b.Navigation("PriceListItems");

                    b.Navigation("ReferenceRanges");

                    b.Navigation("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.TestGroup", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.TestParameter", b =>
                {
                    b.Navigation("ResultValues");
                });

            modelBuilder.Entity("Open_lab.Models.Unit", b =>
                {
                    b.Navigation("TestParameters");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Open_lab.Models.User", b =>
                {
                    b.Navigation("AttendanceDayStatuses");

                    b.Navigation("AttendanceLogs");

                    b.Navigation("AuditLogs");

                    b.Navigation("Payments");

                    b.Navigation("SampleCollections");

                    b.Navigation("UserRoles");

                    b.Navigation("VerifiedResults");
                });

            modelBuilder.Entity("Open_lab.Models.Visit", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("VisitTests");
                });

            modelBuilder.Entity("Open_lab.Models.VisitTest", b =>
                {
                    b.Navigation("ExternalQueueItem");

                    b.Navigation("ResultValues");

                    b.Navigation("SampleCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
